fastcoll:
	g++ -O3 *.cpp -I /opt/homebrew/Cellar/boost/1.82.0_1/include -L /opt/homebrew/Cellar/boost/1.82.0_1/lib -lboost_filesystem -lboost_program_options -lboost_system -o fastcoll
fastcoll-static:
	g++ -O3 *.cpp -I /opt/homebrew/Cellar/boost/1.82.0_1/include -L /opt/homebrew/Cellar/boost/1.82.0_1/lib -l:libboost_filesystem.a -l:libboost_program_options.a -l:libboost_system.a -o fastcoll